#!/usr/bin/env python3
"""Generate VSCode theme artifacts from the canonical theme data in
`comms/shared/theming/lex-theme.json`.

Two artifacts are kept in sync:

1. `package.json` — the dark-mode defaults block under
   `contributes.configurationDefaults.editor.semanticTokenColorCustomizations.rules`.
   These apply automatically on extension activation without writing
   to the user's settings.json.

2. `src/theme-data.ts` — light-mode rules consumed at runtime by
   `src/theme.ts`'s `applyLexTheme()`, which writes them to user
   settings when VSCode is in a light theme and removes them on
   switch back to dark.

Both lists carry the same `<TokenId>:lex` keys; only the colors differ.
The `:lex` suffix is a VSCode language-scope filter (declared in
`semanticTokenScopes`) that prevents the override from leaking into
files of other languages.

VSCode's `semanticTokenColorCustomizations` does not support a
background field. The canonical `background` hint on `VerbatimContent`
is silently ignored here.

Run after editing the canonical file. The build's `prebuild` npm
hook runs `gen-theme.py --check` to fail on stale output.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
CANONICAL = REPO_DIR / "comms" / "shared" / "theming" / "lex-theme.json"
PACKAGE_JSON = REPO_DIR / "package.json"
THEME_DATA_TS = REPO_DIR / "src" / "theme-data.ts"


def load_canonical() -> dict:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


def font_style(token: dict) -> str | None:
    """VSCode encodes font styles as a space-separated string in fontStyle."""
    styles = token.get("styles", [])
    return " ".join(styles) if styles else None


def render_rules(canonical: dict, mode: str) -> dict[str, str | dict]:
    """Build the `rules` dict for a given mode (`light` or `dark`).

    A token with no styles becomes a bare color string; with styles, it
    becomes `{foreground, fontStyle}`. VSCode accepts both forms.
    """
    palette = canonical["intensities"]
    rules: dict[str, str | dict] = {}
    for token_id, token in canonical["tokens"].items():
        color = palette[token["intensity"]][mode]
        fs = font_style(token)
        key = f"{token_id}:lex"
        if fs:
            rules[key] = {"foreground": color, "fontStyle": fs}
        else:
            rules[key] = color
    return rules


def render_package_json_rules(canonical: dict) -> dict[str, str | dict]:
    return render_rules(canonical, "dark")


def render_theme_data_ts(canonical: dict) -> str:
    """Emit a TypeScript file with light-mode rules and the key list.

    The key list is used by `src/theme.ts` to remove light-mode
    overrides from user settings when switching back to dark.

    Output style matches the repo's prettier config (singleQuote,
    tabWidth=2) so prettier round-trips this file unchanged.
    """
    light_rules = render_rules(canonical, "light")
    keys = list(light_rules.keys())

    def s(value: str) -> str:
        # Single-quoted string literal (prettier singleQuote: true).
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"

    def emit_value(v):
        if isinstance(v, str):
            return s(v)
        items = [f"foreground: {s(v['foreground'])}"]
        if "fontStyle" in v:
            items.append(f"fontStyle: {s(v['fontStyle'])}")
        return "{ " + ", ".join(items) + " }"

    rule_lines = [f"  {s(k)}: {emit_value(v)}," for k, v in light_rules.items()]
    key_lines = [f"  {s(k)}," for k in keys]

    body = "\n".join(rule_lines)
    keylist = "\n".join(key_lines)

    return (
        "// Generated by app-bin/gen-theme.py from\n"
        "// comms/shared/theming/lex-theme.json. Do not edit by hand.\n"
        "//\n"
        "// Light-mode semantic-token rules and the full key list. The\n"
        "// runtime in src/theme.ts writes LIGHT_RULES to user settings\n"
        "// when VSCode is in a light theme and removes the LEX_RULE_KEYS\n"
        "// when switching back to dark (so the package.json dark defaults\n"
        "// take over again).\n"
        "\n"
        "export type SemanticTokenRule = string | { foreground: string; fontStyle?: string };\n"
        "\n"
        "export const LIGHT_RULES: Record<string, SemanticTokenRule> = {\n"
        f"{body}\n"
        "};\n"
        "\n"
        "export const LEX_RULE_KEYS: string[] = [\n"
        f"{keylist}\n"
        "];\n"
    )


def package_json_rules_path(data: dict) -> dict[str, str | dict]:
    """Walk into the dark-rules subtree of a parsed package.json."""
    return data["contributes"]["configurationDefaults"][
        "editor.semanticTokenColorCustomizations"
    ]["rules"]


def update_package_json(canonical: dict) -> str:
    """Read package.json, update the dark-defaults rules block, return new
    serialized text. Does not write to disk — caller decides."""
    raw = PACKAGE_JSON.read_text(encoding="utf-8")
    data = json.loads(raw)
    contributes = data["contributes"]
    config_defaults = contributes["configurationDefaults"]
    sem_customizations = config_defaults["editor.semanticTokenColorCustomizations"]
    sem_customizations["rules"] = render_package_json_rules(canonical)
    return json.dumps(data, indent=2) + "\n"


def main() -> int:
    if not CANONICAL.exists():
        print(
            f"FAIL: canonical theme not found at {CANONICAL.relative_to(REPO_DIR)}.\n"
            f"      Did you forget `git submodule update --init`?",
            file=sys.stderr,
        )
        return 1

    canonical = load_canonical()
    expected_pkg_rules = render_package_json_rules(canonical)
    expected_ts = render_theme_data_ts(canonical)

    if "--check" in sys.argv:
        # Compare the dark-rules subtree only — comparing the full
        # serialized package.json text was brittle to unrelated edits
        # (whitespace, key ordering elsewhere, prettier reformat, etc.).
        actual_pkg = json.loads(PACKAGE_JSON.read_text(encoding="utf-8"))
        actual_pkg_rules = package_json_rules_path(actual_pkg)
        if actual_pkg_rules != expected_pkg_rules:
            print(
                f"FAIL: {PACKAGE_JSON.relative_to(REPO_DIR)} dark-mode rules out of sync.\n"
                f"      Run: python app-bin/gen-theme.py",
                file=sys.stderr,
            )
            return 1
        # theme-data.ts is wholly generated by this script (no hand-edits
        # expected), so a full-text compare is appropriate here.
        actual_ts = (
            THEME_DATA_TS.read_text(encoding="utf-8") if THEME_DATA_TS.exists() else ""
        )
        if actual_ts != expected_ts:
            print(
                f"FAIL: {THEME_DATA_TS.relative_to(REPO_DIR)} out of sync.\n"
                f"      Run: python app-bin/gen-theme.py",
                file=sys.stderr,
            )
            return 1
        print(f"  ✓ {PACKAGE_JSON.relative_to(REPO_DIR)} matches generator")
        print(f"  ✓ {THEME_DATA_TS.relative_to(REPO_DIR)} matches generator")
        return 0

    PACKAGE_JSON.write_text(update_package_json(canonical), encoding="utf-8")
    THEME_DATA_TS.parent.mkdir(parents=True, exist_ok=True)
    THEME_DATA_TS.write_text(expected_ts, encoding="utf-8")
    print(f"wrote {PACKAGE_JSON.relative_to(REPO_DIR)}")
    print(f"wrote {THEME_DATA_TS.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
