// Generated by scripts/gen-theme.py from
// comms/shared/theming/lex-theme.json. Do not edit by hand.
//
// Light-mode semantic-token rules and the full key list. The
// runtime in src/theme.ts writes LIGHT_RULES to user settings
// when VSCode is in a light theme and removes the LEX_RULE_KEYS
// when switching back to dark (so the package.json dark defaults
// take over again).

export type SemanticTokenRule = string | { foreground: string; fontStyle?: string };

export const LIGHT_RULES: Record<string, SemanticTokenRule> = {
  'DocumentTitle:lex': { foreground: '#000000', fontStyle: 'bold underline' },
  'DocumentSubtitle:lex': { foreground: '#000000', fontStyle: 'italic' },
  'SessionTitleText:lex': { foreground: '#000000', fontStyle: 'bold' },
  'SessionMarker:lex': { foreground: '#808080', fontStyle: 'italic' },
  'DefinitionSubject:lex': { foreground: '#000000', fontStyle: 'italic' },
  'DefinitionContent:lex': '#000000',
  'ListMarker:lex': { foreground: '#808080', fontStyle: 'italic' },
  'ListItemText:lex': '#000000',
  'InlineStrong:lex': { foreground: '#000000', fontStyle: 'bold' },
  'InlineEmphasis:lex': { foreground: '#000000', fontStyle: 'italic' },
  'InlineCode:lex': '#000000',
  'InlineMath:lex': { foreground: '#000000', fontStyle: 'italic' },
  'Reference:lex': { foreground: '#808080', fontStyle: 'underline' },
  'ReferenceCitation:lex': { foreground: '#808080', fontStyle: 'underline' },
  'ReferenceFootnote:lex': { foreground: '#808080', fontStyle: 'underline' },
  'ReferenceAnnotation:lex': { foreground: '#808080', fontStyle: 'underline' },
  'AnnotationLabel:lex': '#b3b3b3',
  'AnnotationParameter:lex': '#b3b3b3',
  'AnnotationContent:lex': '#b3b3b3',
  'VerbatimSubject:lex': '#b3b3b3',
  'VerbatimLanguage:lex': '#b3b3b3',
  'VerbatimAttribute:lex': '#b3b3b3',
  'VerbatimContent:lex': '#000000',
  'InlineMarker_strong_start:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_strong_end:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_emphasis_start:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_emphasis_end:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_code_start:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_code_end:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_math_start:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_math_end:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_ref_start:lex': { foreground: '#cacaca', fontStyle: 'italic' },
  'InlineMarker_ref_end:lex': { foreground: '#cacaca', fontStyle: 'italic' },
};

export const LEX_RULE_KEYS: string[] = [
  'DocumentTitle:lex',
  'DocumentSubtitle:lex',
  'SessionTitleText:lex',
  'SessionMarker:lex',
  'DefinitionSubject:lex',
  'DefinitionContent:lex',
  'ListMarker:lex',
  'ListItemText:lex',
  'InlineStrong:lex',
  'InlineEmphasis:lex',
  'InlineCode:lex',
  'InlineMath:lex',
  'Reference:lex',
  'ReferenceCitation:lex',
  'ReferenceFootnote:lex',
  'ReferenceAnnotation:lex',
  'AnnotationLabel:lex',
  'AnnotationParameter:lex',
  'AnnotationContent:lex',
  'VerbatimSubject:lex',
  'VerbatimLanguage:lex',
  'VerbatimAttribute:lex',
  'VerbatimContent:lex',
  'InlineMarker_strong_start:lex',
  'InlineMarker_strong_end:lex',
  'InlineMarker_emphasis_start:lex',
  'InlineMarker_emphasis_end:lex',
  'InlineMarker_code_start:lex',
  'InlineMarker_code_end:lex',
  'InlineMarker_math_start:lex',
  'InlineMarker_math_end:lex',
  'InlineMarker_ref_start:lex',
  'InlineMarker_ref_end:lex',
];
